movies = [
    {
        "Title": "They Shall Not Grow Old",
        "Year": 2018,
        "Rated": "R",
        "Released": "01 Feb 2019",
        "Runtime": 99,
        "Genre": "Documentary, History, War",
        "Director": "Peter Jackson",
        "Actors": "Mark Kermode, Peter Jackson",
        "Plot": "A documentary about World War I with never-before-seen footage to commemorate the centennial of the end of the war.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZThmYzUtNDJhOC00ZWY4LThiNmMtZDgxNjE3Yzk4NDU1XkEyXkFqcGdeQXVyNTk5Nzg1NjQ@._V1_SX300.jpg",

      },
      {
        "Title": "Midnight Family",
        "Year": 2019,
        "Rated": "N/A",
        "Released": "06 Dec 2019",
        "Runtime": 81,
        "Genre": "Documentary, Action, Crime, Drama",
        "Director": "Luke Lorentzen",
        "Writer": "Luke Lorentzen",
        "Actors": "Fer Ochoa, Josue Ochoa, Juan Ochoa",
        "Plot": "In Mexico City's wealthiest neighborhoods, the Ochoa family runs a private ambulance, competing with other for-profit EMTs for patients in need of urgent help.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMGYyZTk5MjYtNGY2ZS00NzRhLTgwMWMtZjhmMmQ4OGFkNTNiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      },
      {
        "Title": "Pain & Gain",
        "Year": 2013,
        "Rated": "R",
        "Released": "26 Apr 2013",
        "Runtime": 129,
        "Genre": "Action, Comedy, Crime, Drama",
        "Director": "Michael Bay",
        "Writer": "Christopher Markus (screenplay), Stephen McFeely (screenplay), Pete Collins (based on the magazine articles by)",
        "Actors": "Mark Wahlberg, Dwayne Johnson, Anthony Mackie, Tony Shalhoub",
        "Description": "A trio of bodybuilders in Florida get caught up in an extortion ring and a kidnapping scheme that goes terribly wrong.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTU0NDE5NTU0OV5BMl5BanBnXkFtZTcwMzI1OTMzOQ@@._V1_SX300.jpg",
      },
      {
        "Title": "The Irishman",
        "Year": 2019,
        "Rated": "R",
        "Released": "27 Nov 2019",
        "Runtime": 209,
        "Genre": "Biography, Crime, Drama",
        "Director": "Martin Scorsese",
        "Writer": "Steven Zaillian (screenplay), Charles Brandt (book)",
        "Actors": "Robert De Niro, Al Pacino, Joe Pesci, Harvey Keitel",
        "Plot": "A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMGUyM2ZiZmUtMWY0OC00NTQ4LThkOGUtNjY2NjkzMDJiMWMwXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg",
      {
        "Title": "Once Upon a Time... in Hollywood",
        "Year": 2019,
        "Rated": "R",
        "Released": "26 Jul 2019",
        "Runtime": 161,
        "Genre": "Comedy, Drama",
        "Director": "Quentin Tarantino",
        "Writer": "Quentin Tarantino",
        "Actors": "Leonardo DiCaprio, Brad Pitt, Margot Robbie, Emile Hirsch",
        "Description": "A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg",
      },
      {
        "Title": "Marriage Story",
        "Year": 2019,
        "Rated": "R",
        "Released": "06 Dec 2019",
        "Runtime": 137,
        "Genre": "Comedy, Drama, Romance",
        "Director": "Noah Baumbach",
        "Writer": "Noah Baumbach",
        "Actors": "Adam Driver, Scarlett Johansson, Julia Greer, Azhy Robertson",
        "Plot": "Noah Baumbach's incisive and compassionate look at a marriage breaking up and a family staying together.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZGVmY2RjNDgtMTc3Yy00YmY0LTgwODItYzBjNWJhNTRlYjdkXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg",
      },
      {
        "Title": "Little Women",
        "Year": 1994,
        "Rated": "PG",
        "Released": "25 Dec 1994",
        "Runtime": 115,
        "Genre": "Drama, Family, Romance",
        "Director": "Gillian Armstrong",
        "Writer": "Louisa May Alcott (novel), Robin Swicord (screenplay)",
        "Actors": "Winona Ryder, Gabriel Byrne, Trini Alvarado, Samantha Mathis",
        "Plot": "The March sisters live and grow in post-Civil War America.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNmJhNTgzMWYtZTU5OC00MmE2LTlkN2UtNWE0MmJiNWJmNmZjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
      },
      {
        "Title": "Parasite",
        "Year": 2019,
        "Rated": "R",
        "Released": "08 Nov 2019",
        "Runtime": 132,
        "Genre": "Comedy, Drama, Thriller",
        "Director": "Bong Joon Ho",
        "Writer": "Bong Joon Ho (story), Bong Joon Ho (screenplay), Bong Joon Ho (story by), Jin Won Han (screenplay)",
        "Actors": "Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo, Woo-sik Choi",
        "Plot": "All unemployed, Ki-taek and his family take peculiar interest in the wealthy and glamorous Parks, as they ingratiate themselves into their lives and get entangled in an unexpected incident.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
      },
      {
        "Title": "Knives Out",
        "Year": 2019,
        "Rated": "PG-13",
        "Released": "27 Nov 2019",
        "Runtime": 130,
        "Genre": "Comedy, Crime, Drama, Mystery, Thriller",
        "Director": "Rian Johnson",
        "Actors": "Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis",
        "Plot": "A detective investigates the death of a patriarch of an eccentric, combative family.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg",
      },
      {
        "title": "Dolemite Is My Name",
        "release_date": 2019,
        "rating": "R",
        "Released": "25 Oct 2019",
        "Runtime": 118,
        "Genre": "Biography, Comedy, Drama",
        "Director": "Craig Brewer",
        "Writer": "Scott Alexander, Larry Karaszewski",
        "Actors": "Eddie Murphy, Keegan-Michael Key, Mike Epps, Craig Robinson",
        "Description": "Eddie Murphy portrays real-life legend Rudy Ray Moore, a comedy and rap pioneer who proved naysayers wrong when his hilarious, obscene, kung-fu fighting alter ego, Dolemite, became a 1970s Blaxploitation phenomenon.",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMzFiYWQxYzgtOThmYi00ZmIwLWFlZWMtMzk2NTI2YTYzMjkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",

      }

]

t.string :title
t.string :image_url
t.integer :rating
t.string :genre
t.integer :run_time
t.integer :overall_review
t.datetime :release_date
